#!/usr/bin/env bash
# Switch foot terminal to dark theme using SIGUSR1 signal
# Targets foot server process to update all clients instantly

# Send SIGUSR1 to foot server to switch to [colors] section (dark theme)
# Run in background subshell to avoid signal propagation issues with darkman
(pgrep -x foot | xargs -r kill -SIGUSR1) &
exit 0
